package cn.meteor.module.core.openApi.response;

public enum ErrorType {
	
	//错误码小于100的平台级错误
	UPLOAD_FAIL,
	APP_CALL_LIMITED,
	HTTP_ACTION_NOT_ALLOWED,
	SERVICE_CURRENTLY_UNAVAILABLE,
	INSUFFICIENT_ISV_PERMISSIONS,
	INSUFFICIENT_USER_PERMISSIONS,
	INSUFFICIENT_PARTNER_PERMISSIONS,
	MISSING_METHOD,
	INVALID_METHOD,
	INVALID_FORMAT,
	MISSING_SIGNATURE,
	INVALID_SIGNATURE,
	MISSING_SESSION,
	INVALID_SESSION,
	MISSING_APP_KEY,
	INVALID_APP_KEY,
	MISSING_TIMESTAMP,
	INVALID_TIMESTAMP,
	MISSING_VERSION,
	INVALID_VERSION,
	UNSUPPORTED_VERSION,
	INSUFFICIENT_SESSION_PERMISSIONS,
	PARAMETER_ERROR,
	INVALID_ENCODING,
	
	MISSING_SIGN_METHOD,
	INVALID_SIGN_METHOD,
	
	INVALID_BUSINESS_PARAMETER,
	
	BUSSINESS_ERROR,//业务级错误(父级)
	
	
	//平台级子错误
	ISP_SERVICE_UNAVAILABLE,
	ISP_REMOTE_SERVICE_ERROR,
	ISP_REMOTE_SERVICE_TIMEOUT,
	ISP_REMOTE_CONNECTION_ERROR,
	ISP_NULL_POINTER_EXCEPTION,
	ISP_MOP_PARSE_ERROR,
	ISP_MOP_REMOTE_CONNECTION_TIMEOUT,
	ISP_MOP_REMOTE_CONNECTION_ERROR,
	ISP_MOP_MAPPING_PARSE_ERROR,
	ISP_UNKNOWN_ERROR,
	
	ISP_HIBERNATE_ERROR,
	ISP_SEARCH_ENGINE,
	
	

	//业务级子错误
	ISV_NOT_EXIST,
    ISV_MISSING_PARAMETER,
    ISV_PARAMETER_BLANK,
    ISV_INVALID_PARAMETER,
    ISV_INVALID_PERMISSION,
    ISV_PARAMETERS_MISMATCH,
    ISV_SERVICE_ERROR;
    
}
